spring:
  application:
    name: demo-metrics-app

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  otlp:
    metrics:
      export:
        enabled: true
        url: http://localhost:4318/v1/metrics
        step: 15s
  metrics:
    tags:
      application: ${spring.application.name}
      environment: local
